kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: yeti
spec:
  template:
    metadata:
      labels:
        yeti: yeti-web
    spec:
      containers:
        - name: yeti
          command:
            - bash
            - -c
            - "/usr/local/bin/uwsgi -b 32768 --http 0.0.0.0:8080 -w yeti --callable webapp --processes 4 --stats 0.0.0.0:9191 --stats-http --max-requests 100 --lazy-apps"
          resources:
            limits:
              cpu: 1500m
              memory: 512Mi
            requests:
              cpu: 1000m
              memory: 256Mi
          securityContext:
            runAsUser: 999
            runAsGroup: 1000
          volumeMounts:
            - mountPath: /var/log
              name: logs
          ports:
            - name: noauth
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /observable/
              port: noauth
            initialDelaySeconds: 120
          readinessProbe:
            httpGet:
              path: /observable/
              port: noauth
        - name: keycloak-gatekeeper
          image: quay.io/keycloak/keycloak-gatekeeper
          securityContext:
            runAsUser: 1001
          env:
            - name: PROXY_CLIENT_ID
              value: yeti
            - name: PROXY_UPSTREAM_URL
              value: http://localhost:8080
          envFrom:
            - secretRef:
                name: yeti-keycloak
            - configMapRef:
                name: keycloak-conf
          ports:
            - name: http
              containerPort: 8082
          livenessProbe:
            httpGet:
              path: /oauth/health
              port: http
          readinessProbe:
            httpGet:
              path: /oauth/health
              port: http
      volumes:
        - name: logs
          emptyDir: {}
