apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./../yeti-base
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - networkpolicy-ingress.yaml
  - networkpolicy-huggin.yaml

patchesStrategicMerge:
  - deployment.yaml

secretGenerator:
  - name: yeti-keycloak
    env: keycloak-secret.env

nameSuffix: "-web"
