apiVersion: v1
kind: Service
metadata:
  name: yeti
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: http
    - name: noauth
      port: 3001
      protocol: TCP
      targetPort: noauth
  selector:
    yeti: yeti-web
