apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./yeti
  - ./huginn

patches:
  - path: uptime-patch.yaml
    target:
      kind: Deployment
  - path: imagepull-patch.yaml
    target:
      kind: Deployment
  - path: security-policy-patch.yaml
    target:
      kind: Deployment

configMapGenerator:
  - name: keycloak-conf
    env: keycloak-config.env

images:
  - name: image_prefix
    newName: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/cto/csoc-poc
