kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: yeti
spec:
  replicas: 1
  selector:
    matchLabels:
      name: yeti
  template:
    metadata:
      labels:
        name: yeti
        app: yeti
    spec:
      containers:
        - image: image_prefix:yeti
          name: yeti
          volumeMounts:
            - mountPath: /opt/yeti/yeti.conf
              name: config
              subPath: yeti.conf
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: yeti-conf
