apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./postgres
  - deployment-web.yaml
  - deployment-worker.yaml
  - hpa-web.yaml
  - hpa-worker.yaml
  - ingress.yaml
  - service.yaml
  - networkpolicy.yaml

secretGenerator:
  - name: huggin
    env: huggin-secrets.env
  - name: huggin-keycloak
    env: keycloak-secret.env
