kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: yeti
spec:
  template:
    spec:
      containers:
        - name: yeti
          command:
            - sh
            - -c
            - "/usr/local/bin/celery -A core.config.celeryctl.celery_app worker -Ofair --autoscale=10,2 -Q exports -n exports --purge"
