kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: yeti
spec:
  template:
    spec:
      containers:
        - name: yeti
          securityContext:
            runAsUser: 999
            runAsGroup: 1000
          command:
            # - docker-entrypoint.sh
            # - oneshot
            - bash
            - -c
            - "/usr/local/bin/celery -A core.config.celeryctl.celery_app worker --autoscale=4,2 -Q oneshot -n oneshot --purge"
