kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: yeti
spec:
  template:
    spec:
      containers:
        - name: yeti
          command:
            - sh
            - -c
            - "/usr/local/bin/celery --pidfile=/tmp/celerybeat.pid -A core.config.celeryctl beat -S core.scheduling.Scheduler"
